version: "3.9"

services:
  # Python API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: [.env]
    container_name: scholarship-server
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      es:
        condition: service_healthy
    volumes:
      - ./secrets/firebase_key.json:/run/secrets/firebase_key.json:ro

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: scholarship-elasticsearch
    env_file: [.env]
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - logger.level=ERROR
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0

volumes:
  esdata:
