version: "3.9"

services:
  # Python API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: [.env]
    container_name: scholarship-server
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - elasticsearch
    volumes:
      - ./secrets/firebase_key.json:/run/secrets/firebase_key.json:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: scholarship-elasticsearch
    env_file: [.env]
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
